apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-2
  labels:
    app: hello-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hello-app-2
  template:
    metadata:
      labels:
        app: hello-app-2
        service: hello-app-2
    spec:
      containers:
        - name: hello-app-2
          image: pedrovala/minimalapi:2.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Production"    
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app-2
  labels:
    app: hello-app-2
    service: hello-app-2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: hello-app-2